# Generated by Django 4.2.20 on 2026-09-22 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=255, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('clauses', models.JSONField()),
                ('analysis', models.JSONField()),
                ('processing_time_ms', models.FloatField()),
                ('model_used', models.CharField(choices=[('sbert', 'Sentence-BERT'), ('roberta', 'RoBERTa')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document_id'], name='analyzer_an_documen_8f3167_idx'), models.Index(fields=['-created_at'], name='analyzer_an_created_2b63a7_idx'), models.Index(fields=['owner', '-created_at'], name='analyzer_an_owner_i_b8d17d_idx')],
            },
        ),
    ]
